// Code generated by "stringer -type=Direction"; DO NOT EDIT

package timeutil

import "fmt"

const _Direction_name = "ForwardBackwardEither"

var _Direction_index = [...]uint8{0, 7, 15, 21}

func (i Direction) String() string {
	if i >= Direction(len(_Direction_index)-1) {
		return fmt.Sprintf("Direction(%d)", i)
	}
	return _Direction_name[_Direction_index[i]:_Direction_index[i+1]]
}
